---
- name: Converge
  hosts: all
  become: true

  vars:
    - group_list:
        - name: group01
          gid: 1001
        - name: group02
        - name: group03
          system: true
        - name: group04
          state: absent

  roles:
    - ansible-role-group

  post_tasks:
    # Test if the groups are present
    - name: Test group 1
      shell: /usr/bin/getent group group01
      register: group01_status
      changed_when: "group01_status.rc != 0"
    - name: Test group 2
      shell: /usr/bin/getent group group02
      register: group02_status
      changed_when: "group02_status.rc != 0"
    - name: Test group 3
      shell: /usr/bin/getent group group03
      register: group03_status
      changed_when: "group03_status.rc != 0"

    # Test if the group is absent
    - name: Test group 4
      shell: /usr/bin/getent group group04
      register: group04_status
      failed_when: group04_status.rc != 2
      changed_when: "group04_status.rc != 2"
